---
- name: create temporary file
  tempfile:
  register: temp

- name: download installer script
  get_url:
    url: "{{ haskell_stack_installer_url }}"
    dest: "{{ temp.path }}"
    mode: a+x

- name: run installer script
  script: "{{ temp.path }}"
