---
- name: check stack installed
  command: stack --version
  register: stack_version
  failed_when: no
  changed_when: stack_version.rc != 0

- name: try stack upgrade
  when: stack_version is not changed
  command: stack upgrade
  register: stack_upgrade
  changed_when: |
    'Skipping binary upgrade, you are already running the most recent version'
    not in stack_upgrade.stderr

- set_fact:
    haskell_stack_installed: "{{ stack_version is not changed or stack_upgrade is not failed }}"

- import_tasks: linux.yml
  when: not haskell_stack_installed
